/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HomePage: typeof import('./src/components/homePage/index.vue')['default']
    LeslieMenu: typeof import('./src/components/leslie-Menu/index.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
  }
}
