/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddNote: typeof import('./src/components/addNote/index.vue')['default']
    Classification: typeof import('./src/components/classification/index.vue')['default']
    Comment: typeof import('./src/components/comment/index.vue')['default']
    ContentDetail: typeof import('./src/components/contentDetail/index.vue')['default']
    ContentList: typeof import('./src/components/contentList/index.vue')['default']
    HomePage: typeof import('./src/components/homePage/index.vue')['default']
    LeftOperate: typeof import('./src/components/leslieUI/left-operate/index.vue')['default']
    LeslieButton: typeof import('./src/components/leslieUI/leslie-button/index.vue')['default']
    LeslieConfirm: typeof import('./src/components/leslieUI/leslie-confirm/index.vue')['default']
    LeslieForm: typeof import('./src/components/leslieUI/leslie-form/index.vue')['default']
    LeslieInput: typeof import('./src/components/leslieUI/leslie-input/index.vue')['default']
    LeslieMenu: typeof import('./src/components/leslieUI/leslie-Menu/index.vue')['default']
    LeslieMessage: (typeof import("./src/components/leslieUI/leslie-message/index.vue"))["default"]
    LeslieOption: typeof import('./src/components/leslieUI/leslie-option/index.vue')['default']
    LesliePanel: typeof import('./src/components/leslieUI/leslie-panel/index.vue')['default']
    LesliePopover: typeof import('./src/components/leslieUI/leslie-popover/index.vue')['default']
    LeslieRadio: typeof import('./src/components/leslieUI/leslie-radio/index.vue')['default']
    LeslieSelect: typeof import('./src/components/leslieUI/leslie-select/index.vue')['default']
    Recommend: typeof import('./src/components/recommend/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/leslieUI/svgIcon/index.vue')['default']
  }
}
