/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AddNote: (typeof import("./src/components/addNote/index.vue"))["default"];
    Classification: (typeof import("./src/components/classification/index.vue"))["default"];
    ContentDetail: (typeof import("./src/components/contentDetail/index.vue"))["default"];
    ContentList: (typeof import("./src/components/contentList/index.vue"))["default"];
    ElMenu: (typeof import("element-plus/es"))["ElMenu"];
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
    HomePage: (typeof import("./src/components/homePage/index.vue"))["default"];
    LeftOperate: (typeof import("./src/components/left-operate/index.vue"))["default"];
    LeslieButton: (typeof import("./src/components/leslie-button/index.vue"))["default"];
    LeslieMenu: (typeof import("./src/components/leslie-Menu/index.vue"))["default"];
    Recommend: (typeof import("./src/components/recommend/index.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    SvgIcon: (typeof import("./src/components/svgIcon/index.vue"))["default"];
  }
}
